stages:
  - install
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

services:
  - postgres

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

install:
  image: node:16-alpine
  stage: install
  tags:
    - docker
  script:
    - yarn install

test:
  stage: test
  tags:
    - docker
  script:
    - yarn test:ci

build-dev:
  stage: build
  only:
    - develop
  tags:
    - shell
  script:
    - docker build --target production-stage -t pumpkin-api .

build-prod:
  services:
    - docker:dind
  image: docker:20.10.8
  stage: build
  only:
    - master
  tags:
    - docker
  script:
    - docker build --target production-stage -t pumpkin-api .

deploy-dev:
  stage: deploy
  only:
    - develop
  tags:
    - shell
  script:
    - docker stop pumpkin-api
    - docker run -d -p 8090:8090 --name pumpkin-api --rm pumpkin-api

deploy-prod:
  services:
    - docker:dind
  image: docker:20.10.8
  stage: deploy
  only:
    - master
  tags:
    - docker
  script:
    - docker images